version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-batch-fargate-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13v3pefdyn46p"
s3_prefix = "aws-batch-fargate-example"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VpcId=\"vpc-2708bf40\" SubnetIDs=\"subnet-058724041d8b0811a, subnet-0c5df80632215980a\" SecurityGroupIDs=\"sg-90433feb\""
image_repositories = []
